# Generated by Django 4.1.3 on 2022-12-05 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('price', models.IntegerField()),
                ('product_offer', models.IntegerField(default=0)),
                ('unit', models.CharField(choices=[('Kg', 'Kg'), ('litre', 'litre'), ('pack', 'pack'), ('bottle', 'bottle')], default='Kg', max_length=50)),
                ('image_1', models.ImageField(upload_to='photos/products')),
                ('image_2', models.ImageField(blank=True, upload_to='photos/products')),
                ('image_3', models.ImageField(blank=True, upload_to='photos/products')),
                ('image_4', models.ImageField(blank=True, upload_to='photos/products')),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.sub_category')),
            ],
        ),
    ]
