# Generated by Django 4.1.3 on 2022-12-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaivashop', '0005_wishlistitem_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='cart_status',
            field=models.BooleanField(default=False),
        ),
    ]
