# Generated by Django 4.1.3 on 2022-12-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaivashop', '0003_remove_variation_price_multiplier'),
        ('carts', '0003_remove_cartitem_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='jaivashop.variation'),
        ),
    ]
