# Generated by Django 4.1.3 on 2022-12-16 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_account_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
