# Generated by Django 4.1.3 on 2022-12-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='primary_address',
            field=models.BooleanField(default=True),
        ),
    ]
