# Generated by Django 4.1.3 on 2022-12-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_address_primary_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='order_note',
            field=models.CharField(default='', max_length=500),
        ),
    ]
