# Generated by Django 4.1.3 on 2022-12-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_address_order_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pin_code',
            field=models.IntegerField(max_length=20),
        ),
    ]
