# Generated by Django 4.1.3 on 2022-12-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(upload_to='photos/blog')),
            ],
        ),
    ]
